### ISSUE TITLE
Extra Recipies for Stonecutter [Suggestion]

### ISSUE THREAD

**Issue by SpiderKolo** [Rahala/SweetConcrete#2]
First of, I really like this mod. It looks cool, is very simple and have few cool features I would probably like to make use of.
It's just sad that we can't craft new items using Stonecutter.
Concrete is made of Sand and Gravel, sure, but it can be mined with pickaxe like stone... Besides, Stonecutter could be more useful with more recipes.

I did put same request for Terracotta.

**Comment by Angela** [comment]
Hello @SpiderKolo! Thanks for your feedback. 

Stonecutter recipes for slabs, stairs, walls and vertical slabs have been added to the newest version.
